language: php

php:
  - 7.1

install:
  - composer selfupdate
  - composer install

script:
  - phpunit --colors --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls